# 02_Data Preparation and Data Warehouse Loading

This notebook prepares the raw datasets for integration into a dimensional data warehouse.

The workflow includes:

- **Data type standardisation**, ensuring timestamps and numeric fields are correctly formatted  

- **Feature engineering**, deriving variables such as delivery duration, delivery delay, and operational flags  

- **Data transformations**, including merges and aggregations to construct analytical datasets  

- **Intermediate dataset creation**, simplifying transformation and loading operations  

- **Data validation (Great Expectations)**, enforcing constraints such as primary key uniqueness, non-null fields, valid data types, acceptable value ranges, and logical consistency  

- **Data warehouse loading**, inserting validated data into dimension and fact tables  

These steps ensure the data warehouse is structured, validated, and ready for analytical querying and dashboard development.

# 1.Load the Datasets

In [61]:
import os
import pandas as pd

In [62]:
#cd documents/olist_ecommerce/data/raw
os.getcwd()

'/Users/iristhitsar/Documents/olist_ecommerce/notebook'

In [63]:
#load all datasets
df_customers=pd.read_csv('../data/raw/olist_customers_dataset.csv')
df_geolocation=pd.read_csv('../data/raw/olist_geolocation_dataset.csv')
df_order_item=pd.read_csv('../data/raw/olist_order_items_dataset.csv')
df_order_payments=pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
df_order_review=pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
df_orders=pd.read_csv('../data/raw/olist_orders_dataset.csv')
df_products=pd.read_csv('../data/raw/olist_products_dataset.csv')
df_sellers=pd.read_csv('../data/raw/olist_sellers_dataset.csv')
df_product_category=pd.read_csv('../data/raw/product_category_name_translation.csv')

# 2. Data Preparation and Feature Engineering

In [64]:
#merge the english category names for the df_products dataframe
df_products=df_products.merge(
    df_product_category,
    on='product_category_name',
    how='left')

In [65]:
#check the shape of the dataset after merging
df_products.shape

(32951, 10)

In [66]:
#convert review timestamp columns to datetime type
order_review_date_cols=['review_creation_date', 'review_answer_timestamp']

for col in order_review_date_cols:
  df_order_review[col]=pd.to_datetime(
      df_order_review[col],
      errors='coerce'
  )

In [67]:
#convert order timestamp columns to datetime and inspect min/max values of their datetime components
df_orders_datetime_cols=['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

for col in df_orders_datetime_cols:
  df_orders[col]=pd.to_datetime(
      df_orders[col],
      errors='coerce')

In [68]:
#convert the shipping limit date to datetime data type
df_order_item['shipping_limit_date']=pd.to_datetime(
    df_order_item['shipping_limit_date'],
    errors='coerce'
)

In [69]:
#normalise and convert the data type of categorical cols into category

df_orders['order_status']=(
    df_orders['order_status']
    .str.strip()
    .str.lower()
    .astype('category')
)

df_order_payments['payment_type']=(
    df_order_payments['payment_type']
    .str.strip()
    .str.lower()
    .astype('category')
)

In [70]:
#verify column data types after datetime conversion
df_order_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  datetime64[ns]
 6   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 5.3+ MB

In [71]:
#verify the column data type after datetime conversion
df_order_item['shipping_limit_date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 112650 entries, 0 to 112649
Series name: shipping_limit_date
Non-Null Count   Dtype
--------------   -----
112650 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 880.2 KB

In [72]:
#verify column data types after datetime and category conversions
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: category(1), datetime64[ns](5), object(2)
memory usage: 5.4+ MB

In [73]:
#verify payment_type column data type after category conversion
df_order_payments['payment_type'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 103886 entries, 0 to 103885
Series name: payment_type
Non-Null Count   Dtype
--------------   -----
103886 non-null  category
dtypes: category(1)
memory usage: 101.8 KB

In [74]:
#add revenue column to df_order_item
df_order_item['item_revenue']=df_order_item['price']

In [75]:
#inspect dataframe structure after adding the column
df_order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   item_revenue         112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 6.9+ MB

In [76]:
#add freight value cost col for each order item in the order
df_order_item['item_freight_cost']=df_order_item['freight_value']

In [77]:
#inspect dataframe structure after adding the column
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: category(1), datetime64[ns](5), object(2)
memory usage: 5.4+ MB

In [78]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [79]:
#create orders_customers_df by merging customer info into orders
orders_customer_df=df_orders.merge(
    df_customers[['customer_id', 'customer_unique_id', 'customer_zip_code_prefix']],
    on='customer_id',
    how='left'
)

In [80]:
#view the inital rows of the merged dataframe
orders_customer_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195

In [81]:
#inspect the structure of the merged dataframe
orders_customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   customer_unique_id             99441 non-null  object
 9   customer_zip_code_prefix       99441 non-null  int64
dtypes: category(1), datetime64[ns](5), int64(1), object(3)
memory usage: 6.9+ MB

In [82]:
#create a new column for delivery duration (days) from purchase to customer delivery
df_orders['delivery_duration_days']=(df_orders['order_delivered_customer_date']-df_orders['order_purchase_timestamp']).dt.days

In [83]:
#view the inital rows of the new column
df_orders['delivery_duration_days'].head()

0     8.0
1    13.0
2     9.0
3    13.0
4     2.0
Name: delivery_duration_days, dtype: float64

In [84]:
#create a new colum to flag late delivery orders
df_orders['is_late_delivery']=df_orders['order_delivered_customer_date']>df_orders['order_estimated_delivery_date']

In [85]:
#view the inital rows of the new column
df_orders['is_late_delivery'].head()

0    False
1    False
2    False
3    False
4    False
Name: is_late_delivery, dtype: bool

In [86]:
#create a new column to flag failed orders
df_orders['is_failed_order']=df_orders['order_status'].isin(
    ['unavailable', 'canceled']
)

In [87]:
#inspect the dataset after adding new columns
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_duration_days         96476 non-null  float64
 9   is_late_delivery               99441 non-null  bool
 10  is_failed_order                99441 non-null  bool
dtypes: bool(2), category(1), datetime64[ns](5), float64(1), object(2)
memory usage: 6.4+ MB

In [88]:
df_order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   item_revenue         112650 non-null  float64
 8   item_freight_cost    112650 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 7.7+ MB

In [89]:
#merge order-level features into the order items dataframe
df_order_item_enriched=df_order_item.merge(
    df_orders[['order_id', 'order_status', 'delivery_duration_days', 'is_late_delivery', 'is_failed_order']],
    on='order_id',
    how='left'
)

In [90]:
#view the inital rows of the merged dataset
df_order_item_enriched.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_revenue,item_freight_cost,order_status,delivery_duration_days,is_late_delivery,is_failed_order
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,58.90,13.29,delivered,7.0,False,False
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,239.90,19.93,delivered,16.0,False,False
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,199.00,17.87,delivered,7.0,False,False
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,12.99,12.79,delivered,6.0,False,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,199.90,18.14,delivered,25.0,False,False

In [91]:
#check the structure of the merged dataset
df_order_item_enriched.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                112650 non-null  object
 1   order_item_id           112650 non-null  int64
 2   product_id              112650 non-null  object
 3   seller_id               112650 non-null  object
 4   shipping_limit_date     112650 non-null  datetime64[ns]
 5   price                   112650 non-null  float64
 6   freight_value           112650 non-null  float64
 7   item_revenue            112650 non-null  float64
 8   item_freight_cost       112650 non-null  float64
 9   order_status            112650 non-null  category
 10  delivery_duration_days  110196 non-null  float64
 11  is_late_delivery        112650 non-null  bool
 12  is_failed_order         112650 non-null  bool
dtypes: bool(2), category(1), datetime64[ns](1), float64(5), int64(1), object(3)
memory usage: 8.9+ MB

In [92]:
df_geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [93]:
#aggregate average latitude and longitude by zip code
geo_agg_df=(
    df_geolocation
    .groupby('geolocation_zip_code_prefix', as_index=False)
    .agg(
        lat=('geolocation_lat', 'mean'),
        lng=('geolocation_lng', 'mean'),
    )
  )

#merge aggregated geolocation into customers dataFrame
df_customers=df_customers.merge(
    geo_agg_df,
    left_on='customer_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left'
)

#merge aggregated geolocation into sellers dataFrame
df_sellers=df_sellers.merge(
    geo_agg_df,
    left_on='seller_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left'
)

In [94]:
#check the inital rows of the aggreagted geolocation dataframe
geo_agg_df.head()

   geolocation_zip_code_prefix        lat        lng
0                         1001 -23.550190 -46.634024
1                         1002 -23.548146 -46.634979
2                         1003 -23.548994 -46.635731
3                         1004 -23.549799 -46.634757
4                         1005 -23.549456 -46.636733

In [95]:
#check the inital rows of the enriched customer dataframe
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,lat,lng
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,14409.0,-20.498489,-47.396929
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,9790.0,-23.727992,-46.542848
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,1151.0,-23.531642,-46.656289
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,8775.0,-23.499702,-46.185233
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,13056.0,-22.975100,-47.142925

In [96]:
#check the structure of the enriched customer dataframe
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  99441 non-null  object
 1   customer_unique_id           99441 non-null  object
 2   customer_zip_code_prefix     99441 non-null  int64
 3   customer_city                99441 non-null  object
 4   customer_state               99441 non-null  object
 5   geolocation_zip_code_prefix  99163 non-null  float64
 6   lat                          99163 non-null  float64
 7   lng                          99163 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 6.1+ MB

In [97]:
#check the inital rows of the enriched seller dataframe
df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state,geolocation_zip_code_prefix,lat,lng
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,13023.0,-22.893848,-47.061337
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,13844.0,-22.383437,-46.947927
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,20031.0,-22.909572,-43.177703
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,4195.0,-23.657242,-46.612831
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,12914.0,-22.964803,-46.534419

In [98]:
#check the structure of the enriched seller dataframe
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   seller_id                    3095 non-null   object
 1   seller_zip_code_prefix       3095 non-null   int64
 2   seller_city                  3095 non-null   object
 3   seller_state                 3095 non-null   object
 4   geolocation_zip_code_prefix  3088 non-null   float64
 5   lat                          3088 non-null   float64
 6   lng                          3088 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 169.4+ KB

# 3. Data Quality Validation

In [99]:
pip install great_expectations

/opt/anaconda3/lib/python3.13/pty.py:95: DeprecationWarning: This process (pid=97422) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()

Requirement already satisfied: great_expectations in /opt/anaconda3/lib/python3.13/site-packages (1.11.3)
Requirement already satisfied: altair<5.0.0,>=4.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (4.2.2)
Requirement already satisfied: cryptography>=3.2 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (44.0.1)
Requirement already satisfied: jinja2>=3 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (3.1.6)
Requirement already satisfied: jsonschema>=2.5.1 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (4.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (3.26.2)
Requirement already satisfied: mistune>=0.8.4 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (3.1.2)
Requirement already satisfied: numpy>=1.22.4 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (2.1.3)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (24.2)
Requirement already satisfied: pandas<3.0.0,>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (2.2.3)
Requirement already satisfied: pydantic>=1.10.7 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (2.10.3)
Requirement already satisfied: pyparsing!=3.2.4,>=2.4 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (3.2.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (2.9.0.post0)
Requirement already satisfied: requests>=2.20 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (2.32.3)
Requirement already satisfied: ruamel.yaml>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (0.18.10)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (1.15.3)
Requirement already satisfied: tqdm>=4.59.0 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (4.67.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (4.12.2)
Requirement already satisfied: tzlocal>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from great_expectations) (5.3.1)
Requirement already satisfied: entrypoints in /opt/anaconda3/lib/python3.13/site-packages (from altair<5.0.0,>=4.2.1->great_expectations) (0.4)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.13/site-packages (from altair<5.0.0,>=4.2.1->great_expectations) (1.0.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3.0.0,>=1.3.0->great_expectations) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3.0.0,>=1.3.0->great_expectations) (2025.2)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=3.2->great_expectations) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=3.2->great_expectations) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2>=3->great_expectations) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.5.1->great_expectations) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.5.1->great_expectations) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.5.1->great_expectations) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.5.1->great_expectations) (0.22.3)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic>=1.10.7->great_expectations) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic>=1.10.7->great_expectations) (2.27.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.1->great_expectations) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.20->great_expectations) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.20->great_expectations) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.20->great_expectations) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.20->great_expectations) (2026.1.4)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [100]:
#import great expectations library
import great_expectations as gx

#initialise a great expectations context
context=gx.get_context()

In [101]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_duration_days         96476 non-null  float64
 9   is_late_delivery               99441 non-null  bool
 10  is_failed_order                99441 non-null  bool
dtypes: bool(2), category(1), datetime64[ns](5), float64(1), object(2)
memory usage: 6.4+ MB

In [102]:
#create validator for the orders dataframe
validator_orders = gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
            data=df_orders
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="orders_suite"
    )
)

In [103]:
#ensure order_id is unique
validator_orders.expect_column_values_to_be_unique(
    column="order_id"
)

#ensure key fields are not missing
validator_orders.expect_column_values_to_not_be_null(
    column="customer_id"
)

validator_orders.expect_column_values_to_not_be_null(
    column="order_estimated_delivery_date"
)

validator_orders.expect_column_values_to_not_be_null(
    column="order_purchase_timestamp"
)

#validate datetime columns have correct data type
for col in [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]:
    validator_orders.expect_column_values_to_be_of_type(
        column=col,
        type_="datetime64[ns]"
    )
    
#ensure delivery duration is non-negative
validator_orders.expect_column_values_to_be_between(
    column="delivery_duration_days",
    min_value=0,
    mostly=0.97
)

#ensure boolean flags only contain True or False
validator_orders.expect_column_values_to_be_in_set(
    column="is_late_delivery",
    value_set=[True, False],
)

validator_orders.expect_column_values_to_be_in_set(
    column="is_failed_order",
    value_set=[True, False],
)

#validate order status categories
validator_orders.expect_column_values_to_be_in_set(
    column="order_status",
    value_set=[
        "delivered",
        "shipped",
        "canceled",
        "processing",
        "invoiced",
        "unavailable",
        "created",
        "approved"
    ]
)

#run validation
results_orders=validator_orders.validate()

print(results_orders)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/37 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "column": "order_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "customer_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "order_estimated_delivery_date"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "order_estimated_delivery_date",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "order_purchase_timestamp"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "order_purchase_timestamp",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "order_approved_at",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "order_delivered_carrier_date",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "order_delivered_customer_date",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "delivery_duration_days",
          "mostly": 0.97,
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 2965,
        "missing_percent": 2.981667521444877,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_in_set",
        "kwargs": {
          "column": "is_late_delivery",
          "value_set": [
            true,
            false
          ]
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_in_set",
        "kwargs": {
          "column": "is_failed_order",
          "value_set": [
            true,
            false
          ]
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_in_set",
        "kwargs": {
          "column": "order_status",
          "value_set": [
            "delivered",
            "shipped",
            "canceled",
            "processing",
            "invoiced",
            "unavailable",
            "created",
            "approved"
          ]
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "orders_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 13,
    "successful_expectations": 13,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "orders_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:38:34.319403+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T143830.630058Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T143834.319356Z",
    "checkpoint_name": null
  },
  "id": null
}

In [104]:
df_order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   item_revenue         112650 non-null  float64
 8   item_freight_cost    112650 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 7.7+ MB

In [105]:
#create validator for the order_items dataframe
validator_order_items = gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
            data=df_order_item
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="order_item_suite"
    )
)

In [107]:
#ensure composite key (order_id, order_item_id) is unique
validator_order_items.expect_compound_columns_to_be_unique(
    column_list=["order_id", "order_item_id"]
)

#ensure key fields are not missing
validator_order_items.expect_column_values_to_not_be_null(
    column="order_id"
)

validator_order_items.expect_column_values_to_not_be_null(
    column="order_item_id"
)

validator_order_items.expect_column_values_to_not_be_null(
    column="price"
)

validator_order_items.expect_column_values_to_not_be_null(
    column="freight_value"
)

validator_order_items.expect_column_values_to_not_be_null(
    column="item_freight_cost"
)

validator_order_items.expect_column_values_to_not_be_null(
    column="item_revenue"
)

validator_order_items.expect_column_values_to_not_be_null(
    column="shipping_limit_date"
)

#ensure numeric values are non-negative
validator_order_items.expect_column_values_to_be_between(
    column="order_item_id",
    min_value=0,
)

validator_order_items.expect_column_values_to_be_between(
    column="price",
    min_value=0,
)

validator_order_items.expect_column_values_to_be_between(
    column="freight_value",
    min_value=0,
)

validator_order_items.expect_column_values_to_be_between(
    column="item_freight_cost",
    min_value=0,
)

validator_order_items.expect_column_values_to_be_between(
    column="item_revenue",
    min_value=0,
)

#validate business rule relationships between columns
validator_order_items.expect_column_pair_values_to_be_equal(
    column_A='item_revenue',
    column_B='price',
)

validator_order_items.expect_column_pair_values_to_be_equal(
    column_A='item_freight_cost',
    column_B='freight_value',
)

#validate datetime column has correct data type
validator_order_items.expect_column_values_to_be_of_type(
        column="shipping_limit_date",
        type_="datetime64[ns]"
)

#run validation
results_order_items=validator_order_items.validate()

print(results_order_items)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/51 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_compound_columns_to_be_unique",
        "kwargs": {
          "column_list": [
            "order_id",
            "order_item_id"
          ]
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_pair_values_to_be_equal",
        "kwargs": {
          "column_A": "item_revenue",
          "column_B": "price"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_pair_values_to_be_equal",
        "kwargs": {
          "column_A": "item_freight_cost",
          "column_B": "freight_value"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "order_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "order_item_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "order_item_id",
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "price"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "price",
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "freight_value"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "freight_value",
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "item_freight_cost"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "item_freight_cost",
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "item_revenue"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "item_revenue",
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "shipping_limit_date"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 112650,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "shipping_limit_date",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "order_item_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 16,
    "successful_expectations": 16,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "order_item_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:42:31.388416+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T144025.913766Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T144231.388286Z",
    "checkpoint_name": null
  },
  "id": null
}

In [108]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  99441 non-null  object
 1   customer_unique_id           99441 non-null  object
 2   customer_zip_code_prefix     99441 non-null  int64
 3   customer_city                99441 non-null  object
 4   customer_state               99441 non-null  object
 5   geolocation_zip_code_prefix  99163 non-null  float64
 6   lat                          99163 non-null  float64
 7   lng                          99163 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 6.1+ MB

In [109]:
#create validator for the customers dataframe
validator_customers = gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
            data=df_customers
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="customers_suite"
    )
)

In [110]:
#ensure required fields are not missing
validator_customers.expect_column_values_to_not_be_null(
    column="customer_id"
)

validator_customers.expect_column_values_to_not_be_null(
    column="customer_unique_id"
)

validator_customers.expect_column_values_to_not_be_null(
    column="customer_state"
)

#ensure customer_id is unique
validator_customers.expect_column_values_to_be_unique(
    column="customer_id"
)

#ensure zip code prefix values are valid
validator_customers.expect_column_values_to_be_between(
    column="customer_zip_code_prefix",
    min_value=1,
    mostly=0.997,
)

#validate customer_state format
validator_customers.expect_column_values_to_match_regex(
    column="customer_state",
    regex="^[A-Z]{2}$"
)

#ensure geographic coordinates are within valid range
validator_customers.expect_column_values_to_be_between(
    column="lat",
    min_value=-90,
    max_value=90,
    mostly=0.997
)

validator_customers.expect_column_values_to_be_between(
    column="lng",
    min_value=-180,
    max_value=180,
    mostly=0.997
)

#run validation
results_customers=validator_customers.validate()
print(results_customers)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/33 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "customer_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "column": "customer_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "customer_unique_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "customer_state"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_match_regex",
        "kwargs": {
          "column": "customer_state",
          "regex": "^[A-Z]{2}$"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "customer_zip_code_prefix",
          "mostly": 0.997,
          "min_value": 1.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "lat",
          "mostly": 0.997,
          "min_value": -90.0,
          "max_value": 90.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 278,
        "missing_percent": 0.27956275580494966,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "lng",
          "mostly": 0.997,
          "min_value": -180.0,
          "max_value": 180.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99441,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 278,
        "missing_percent": 0.27956275580494966,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "customers_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 8,
    "successful_expectations": 8,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "customers_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:43:32.445188+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T144331.478061Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T144332.445162Z",
    "checkpoint_name": null
  },
  "id": null
}

In [111]:
df_geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [112]:
#create a validator for the geolocation dataframe
validator_geolocation = gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
            data=df_geolocation
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="geolocation_suite"
    )
)

In [113]:
#ensure key fields are not missing
validator_geolocation.expect_column_values_to_not_be_null(
    column="geolocation_zip_code_prefix"
)

validator_geolocation.expect_column_values_to_not_be_null(
    column="geolocation_state"
)

validator_geolocation.expect_column_values_to_not_be_null(
    column="geolocation_city"
)

#ensure zip code prefix values are valid
validator_geolocation.expect_column_values_to_be_between(
    column="geolocation_zip_code_prefix",
    min_value=1,
)

#ensure geographic coordinates are within valid range
validator_geolocation.expect_column_values_to_be_between(
    column="geolocation_lat",
    min_value=-90,
    max_value=90
)

validator_geolocation.expect_column_values_to_be_between(
    column="geolocation_lng",
    min_value=-180,
    max_value=180
)

#validate state code format
validator_geolocation.expect_column_values_to_match_regex(
    column="geolocation_state",
    regex="^[A-Z]{2}$"
)

#run validation
results_geolocation=validator_geolocation.validate()
print(results_geolocation)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/28 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "geolocation_zip_code_prefix"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 1000163,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "geolocation_zip_code_prefix",
          "min_value": 1.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 1000163,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "geolocation_state"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 1000163,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_match_regex",
        "kwargs": {
          "column": "geolocation_state",
          "regex": "^[A-Z]{2}$"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 1000163,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "geolocation_city"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 1000163,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "geolocation_lat",
          "min_value": -90.0,
          "max_value": 90.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 1000163,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "geolocation_lng",
          "min_value": -180.0,
          "max_value": 180.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 1000163,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "geolocation_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 7,
    "successful_expectations": 7,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "geolocation_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:44:12.342566+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T144409.984626Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T144412.342540Z",
    "checkpoint_name": null
  },
  "id": null
}

In [114]:
df_order_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  datetime64[ns]
 6   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 5.3+ MB

In [115]:
#create validator for order review dataframe
validator_order_review = gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
            data=df_order_review
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="order_review_suite"
    )
)

In [116]:
#ensure key fields are not missing
validator_order_review.expect_column_values_to_not_be_null(
    column="review_id"
)

validator_order_review.expect_column_values_to_not_be_null(
    column="order_id"
)

validator_order_review.expect_column_values_to_not_be_null(
    column="review_creation_date"
)

validator_order_review.expect_column_values_to_not_be_null(
    column="review_answer_timestamp"
)

#ensure review scores are within valid range
validator_order_review.expect_column_values_to_be_between(
    column="review_score",
    min_value=1,
    max_value=5
)

#validate datetime columns have correct data type
validator_order_review.expect_column_values_to_be_of_type(
        column="review_creation_date",
        type_="datetime64[ns]"
)

validator_order_review.expect_column_values_to_be_of_type(
        column="review_answer_timestamp",
        type_="datetime64[ns]"
)

#run validation
reults_order_review=validator_order_review.validate()
print(reults_order_review)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/20 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "review_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99224,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "order_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99224,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "review_creation_date"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99224,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "review_creation_date",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "review_answer_timestamp"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99224,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_of_type",
        "kwargs": {
          "column": "review_answer_timestamp",
          "type_": "datetime64[ns]"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "review_score",
          "min_value": 1.0,
          "max_value": 5.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 99224,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "order_review_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 7,
    "successful_expectations": 7,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "order_review_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:45:00.350582+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T144456.679487Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T144500.350501Z",
    "checkpoint_name": null
  },
  "id": null
}

In [117]:
df_order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  category
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: category(1), float64(1), int64(2), object(1)
memory usage: 3.3+ MB

In [118]:
#create validator for order payments dataframe
validator_order_payments = gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
            data=df_order_payments
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="order_payments_suite"
    )
)

In [119]:
#ensure key fields are not missing
validator_order_payments.expect_column_values_to_not_be_null(
    column="order_id"
)

validator_order_payments.expect_column_values_to_not_be_null(
    column="payment_sequential"
)

validator_order_payments.expect_column_values_to_not_be_null(
    column="payment_installments"
)

validator_order_payments.expect_column_values_to_not_be_null(
    column="payment_value"
)

#ensure numeric values are within valid range
validator_order_payments.expect_column_values_to_be_between(
    column="payment_sequential",
    min_value=1,
)

validator_order_payments.expect_column_values_to_be_between(
    column="payment_installments",
    min_value=0,
)

validator_order_payments.expect_column_values_to_be_between(
    column="payment_value",
    min_value=0,
)

#validate payment type categories
validator_order_payments.expect_column_values_to_be_in_set(
    column="payment_type",
    value_set=["credit_card","boleto","voucher","debit_card","not_defined"]
)

#run validation
results_order_payments=validator_order_payments.validate()
print(results_order_payments)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/29 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "order_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "payment_sequential"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "payment_sequential",
          "min_value": 1.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "payment_installments"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "payment_installments",
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "payment_value"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "payment_value",
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_in_set",
        "kwargs": {
          "column": "payment_type",
          "value_set": [
            "credit_card",
            "boleto",
            "voucher",
            "debit_card",
            "not_defined"
          ]
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 103886,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "order_payments_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 8,
    "successful_expectations": 8,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "order_payments_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:45:38.637863+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T144536.915992Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T144538.637833Z",
    "checkpoint_name": null
  },
  "id": null
}

In [120]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_id                     32951 non-null  object
 1   product_category_name          32341 non-null  object
 2   product_name_lenght            32341 non-null  float64
 3   product_description_lenght     32341 non-null  float64
 4   product_photos_qty             32341 non-null  float64
 5   product_weight_g               32949 non-null  float64
 6   product_length_cm              32949 non-null  float64
 7   product_height_cm              32949 non-null  float64
 8   product_width_cm               32949 non-null  float64
 9   product_category_name_english  32328 non-null  object
dtypes: float64(7), object(3)
memory usage: 2.5+ MB

In [122]:
#create validator for products dataframe
validator_products=gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
        data=df_products
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="products_suite"
    )
)

In [123]:
#ensure key fields are not missing
validator_products.expect_column_values_to_not_be_null(
    column="product_id"
)

#ensure product_id is unique
validator_products.expect_column_values_to_be_unique(
    column="product_id"
)

#ensure product dimension values are non-negative
for col in [
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]:
    validator_products.expect_column_values_to_be_between(
        column=col,
        min_value=0,
        mostly=0.99
    )

#ensure product photo counts are non-negative
validator_products.expect_column_values_to_be_between(
    column="product_photos_qty",
    min_value=0,
     mostly=0.99
)

#run validation
results_products=validator_products.validate()
print(results_products)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/34 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "product_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 32951,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "column": "product_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 32951,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "product_weight_g",
          "mostly": 0.99,
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 32951,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 2,
        "missing_percent": 0.006069618524475737,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "product_length_cm",
          "mostly": 0.99,
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 32951,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 2,
        "missing_percent": 0.006069618524475737,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "product_height_cm",
          "mostly": 0.99,
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 32951,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 2,
        "missing_percent": 0.006069618524475737,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "product_width_cm",
          "mostly": 0.99,
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 32951,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 2,
        "missing_percent": 0.006069618524475737,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "product_photos_qty",
          "mostly": 0.99,
          "min_value": 0.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 32951,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 610,
        "missing_percent": 1.8512336499650999,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "products_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 7,
    "successful_expectations": 7,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "products_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:48:51.663117+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T144850.813303Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T144851.663081Z",
    "checkpoint_name": null
  },
  "id": null
}

In [124]:
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   seller_id                    3095 non-null   object
 1   seller_zip_code_prefix       3095 non-null   int64
 2   seller_city                  3095 non-null   object
 3   seller_state                 3095 non-null   object
 4   geolocation_zip_code_prefix  3088 non-null   float64
 5   lat                          3088 non-null   float64
 6   lng                          3088 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 169.4+ KB

In [125]:
#create validator for sellers dataframe
validator_sellers = gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
            data=df_sellers
        )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="sellers_suite"
    )
)

In [126]:
#ensure key fields are not missing
validator_sellers.expect_column_values_to_not_be_null(
    column="seller_id"
)

validator_sellers.expect_column_values_to_not_be_null(
    column="seller_zip_code_prefix"
)

validator_sellers.expect_column_values_to_not_be_null(
    column="seller_state"
)

#ensure seller_id is unique
validator_sellers.expect_column_values_to_be_unique(
    column="seller_id"
)

#ensure zip code prefix values are valid
validator_sellers.expect_column_values_to_be_between(
    column="seller_zip_code_prefix",
    min_value=1,
)

#validate seller_state format
validator_sellers.expect_column_values_to_match_regex(
    column="seller_state",
    regex="^[A-Z]{2}$"
)

#run validation
results_sellers=validator_sellers.validate()
print(results_sellers)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/21 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "seller_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 3095,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "column": "seller_id"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 3095,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "seller_zip_code_prefix"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 3095,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "column": "seller_zip_code_prefix",
          "min_value": 1.0
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 3095,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "seller_state"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 3095,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_match_regex",
        "kwargs": {
          "column": "seller_state",
          "regex": "^[A-Z]{2}$"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 3095,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "sellers_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 6,
    "successful_expectations": 6,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "sellers_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:49:24.998111+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T144924.444570Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T144924.998072Z",
    "checkpoint_name": null
  },
  "id": null
}

In [127]:
df_product_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [129]:
#create a validator for product category name dataframe
validator_product_category=gx.validator.validator.Validator(
    execution_engine=gx.execution_engine.PandasExecutionEngine(),
    batches=[
        gx.core.batch.Batch(
        data=df_product_category
    )
    ],
    expectation_suite=gx.core.expectation_suite.ExpectationSuite(
        name="products_suite"
    )
)

In [130]:
#ensure key fields are not missing
validator_product_category.expect_column_values_to_not_be_null(
    column="product_category_name"
)

validator_product_category.expect_column_values_to_not_be_null(
    column="product_category_name_english"
)


#ensure english category names are unique
validator_product_category.expect_column_values_to_be_unique(
    column="product_category_name_english"
)

#ensure english category names are not empty
validator_product_category.expect_column_value_lengths_to_be_between(
    column="product_category_name_english",
    min_value=1
)

#run validation
results_product_category=validator_product_category.validate()
print(results_product_category)

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/great_expectations/expectations/expectation.py:1633: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/16 [00:00<?, ?it/s]

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "product_category_name"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 71,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "product_category_name_english"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 71,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "column": "product_category_name_english"
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 71,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_value_lengths_to_be_between",
        "kwargs": {
          "column": "product_category_name_english",
          "min_value": 1
        },
        "meta": {},
        "severity": "critical"
      },
      "result": {
        "element_count": 71,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "products_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 4,
    "successful_expectations": 4,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.11.3",
    "expectation_suite_name": "products_suite",
    "run_id": {
      "run_name": null,
      "run_time": "2026-03-16T14:54:00.783088+00:00"
    },
    "batch_spec": {},
    "batch_markers": {
      "ge_load_time": "20260316T145358.341396Z"
    },
    "active_batch_definition": {},
    "validation_time": "20260316T145400.782998Z",
    "checkpoint_name": null
  },
  "id": null
}

# 4. Load the Data into the Dim and Fact Tables

In [131]:
#install PostgreSQL driver and SQL toolkit
!pip install psycopg2-binary sqlalchemy

/opt/anaconda3/lib/python3.13/pty.py:95: DeprecationWarning: This process (pid=97422) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [132]:
#import SQLAlchemy engine
from sqlalchemy import create_engine

#create connection to PostgreSQL data warehouse
engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/olist_dw"
)

In [133]:
#test database connection
engine.connect()

In [ ]:
#function to build date dimension table
def build_dim_date(df_orders, df_order_item):

  #timestamp columns from orders table
  date_cols_orders=[
      'order_purchase_timestamp',
      'order_approved_at',
      'order_delivered_carrier_date',
      'order_delivered_customer_date',
      'order_estimated_delivery_date',
  ]

  #timestamp column from order_items table
  date_cols_items=['shipping_limit_date']

  dates=[]

  #extract date from orders timestamps
  for c in date_cols_orders:
    if c in df_orders.columns:
      dates.append(df_orders[c].dt.date)

  #extract date from order_items timestamps
  for c in date_cols_items:
    if c in df_order_item.columns:
      dates.append(df_order_item[c].dt.date)

  #combine all dates and remove nulls
  all_dates=pd.concat(dates).dropna().unique()

  #create dataframe of unique dates
  df=pd.DataFrame({'full_date':pd.to_datetime(all_dates)})
  df = df.drop_duplicates(subset=['full_date'])
    
  #generate date attributes
  df['date_sk']=df['full_date'].dt.strftime('%Y%m%d').astype(int)
  df['day']=df['full_date'].dt.day
  df['month']=df['full_date'].dt.month
  df['month_name']=df['full_date'].dt.strftime('%B')
  df['quarter']=df['full_date'].dt.quarter
  df['year']=df['full_date'].dt.year
  df['day_of_week']=df['full_date'].dt.weekday+1
  df['is_weekend']=df['day_of_week'].isin([6, 7])

  #return sorted date dimension
  return df.sort_values('full_date')

In [ ]:
#build date dimension dataframe
dim_date_df=build_dim_date(df_orders, df_order_item)
dim_date_df.head()

,full_date,date_sk,day,month,month_name,quarter,year,day_of_week,is_weekend
594,2016-09-04,20160904,4,9,September,3,2016,7,True
593,2016-09-05,20160905,5,9,September,3,2016,1,False
610,2016-09-13,20160913,13,9,September,3,2016,2,False
618,2016-09-15,20160915,15,9,September,3,2016,4,False
717,2016-09-19,20160919,19,9,September,3,2016,1,False

In [ ]:
#check number of rows of the date dimension dataframe
dim_date_df.shape

(720, 9)

In [ ]:
#load date dimension iinto dim.dim_date table
dim_date_df.to_sql(
    'dim_date',
    engine,
    schema='dim',
    if_exists='append',
    index=False
)

720

In [ ]:
#verify rows loaded into database
pd.read_sql(
    "SELECT COUNT(*) AS row_count FROM dim.dim_date",
    engine
)

   row_count
0        720

In [ ]:
#function to build geography dimension
def build_dim_geography(df_geolocation):

  #return most frequent value or null if empty
  def mode_or_null(series):
    s=series.dropna()
    if s.empty:
      return None
    return s.value_counts().idxmax()

  #aggregate geolocation data by zip code prefix
  dim_geo_df=(
      df_geolocation
      .groupby('geolocation_zip_code_prefix', as_index=False)
      .agg(
          city=('geolocation_city', mode_or_null),
          state=('geolocation_state', mode_or_null),
          lat=('geolocation_lat', 'mean'),
          lng=('geolocation_lng', 'mean')
      )
      .rename(columns={'geolocation_zip_code_prefix':'zip_code_prefix'})
  )
  return dim_geo_df

In [ ]:
#build geography dimension dataframe
dim_geo_df=build_dim_geography(df_geolocation)
dim_geo_df.head()

   zip_code_prefix       city state        lat        lng
0             1001  sao paulo    SP -23.550190 -46.634024
1             1002  sao paulo    SP -23.548146 -46.634979
2             1003  sao paulo    SP -23.548994 -46.635731
3             1004  sao paulo    SP -23.549799 -46.634757
4             1005  sao paulo    SP -23.549456 -46.636733

In [ ]:
#check number of rows of dim_geo dataframe
dim_geo_df.shape

(19015, 5)

In [ ]:
#load geography dimension into dim.dim_geography table
dim_geo_df.to_sql(
    "dim_geography",
    engine,
    schema="dim",
    if_exists="append",
    index=False
)

15

In [ ]:
#verify rows loaded into database
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_geography',
    engine
)

   row_count
0      19015

In [ ]:
#function to build customer dimension
def build_dim_customer(customers_df, dim_geo_df):

    #select relevant customer attributes
    dim_customer_df=(
        customers_df.loc[:, [
            'customer_unique_id',
            'customer_zip_code_prefix',
            'customer_city',
            'customer_state'
        ]]
        #ensure one record per unique customer
        .drop_duplicates(subset=['customer_unique_id'])

        #link customer to geography surrogate key
        .merge(
            dim_geo_df[['geo_sk','zip_code_prefix']],
            left_on='customer_zip_code_prefix',
            right_on='zip_code_prefix',
            how='left'
        )
        .rename(columns={'geo_sk':'customer_geo_sk'})

        #remove redundant join column
        .drop(columns=['zip_code_prefix'])
        .reset_index(drop=True)
    )
    return dim_customer_df

In [ ]:
#get geography surrogate keys for customer-geography mapping
dim_geo_df=pd.read_sql(
    'SELECT geo_sk, zip_code_prefix FROM dim.dim_geography;',
    engine
)

#build customer dimension dataframe
dim_customer_df=build_dim_customer(df_customers, dim_geo_df)
dim_customer_df.head()

In [ ]:
#check number of rows of dim_customer dataframe
dim_customer_df.shape

(96096, 5)

In [ ]:
#load customer dimension into dim.dim_customer table
dim_customer_df.to_sql(
    name='dim_customer',
    con=engine,
    schema='dim',
    if_exists='append',
    index=False
)

96

In [ ]:
#verify rows loaded in dim_customer table
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_customer',
    engine
)

   row_count
0      96096

In [ ]:
#function to build seller dimension
def build_dim_seller(df_sellers, geo_dim_df):
    dim_seller_df=(
        df_sellers.loc[:,[
            'seller_id',
            'seller_zip_code_prefix',
            'seller_city',
            'seller_state'
        ]]
        .drop_duplicates(subset=['seller_id'])

        #link seller to geography surrogate key
        .merge(
           geo_dim_df[['geo_sk','zip_code_prefix']], 
            left_on='seller_zip_code_prefix',
            right_on='zip_code_prefix',
            how='left'
        )
        .rename(columns={'geo_sk':'seller_geo_sk'})
        .drop(columns=['zip_code_prefix'])
        .reset_index(drop=True)
    )
    return dim_seller_df

In [ ]:
#get geography surrogate keys for seller-geography mapping
dim_geo_df=pd.read_sql(
    'SELECT geo_sk, zip_code_prefix FROM dim.dim_geography',
    engine
)

#build seller dimension dataframe
dim_seller_df=build_dim_seller(df_sellers, dim_geo_df)
dim_seller_df.head()

In [ ]:
#check number of rows of dim_seller dataframe
dim_seller_df.shape

(3095, 5)

In [ ]:
#load seller dimension into dim.dim_seller table
dim_seller_df.to_sql(
    name='dim_seller',
    con=engine,
    schema='dim',
    if_exists='append',
    index=False
)

95

In [ ]:
#verify rows loaded in dim_seller table
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_seller',
    engine
)

   row_count
0       3095

In [ ]:
#function to build product dimension
def build_dim_product(df_products):
    dim_product_df=(
        df_products.loc[:,[
            'product_id',
            'product_category_name',             
            'product_category_name_english',
            'product_weight_g',
            'product_length_cm',
            'product_height_cm',
            'product_width_cm',
            'product_photos_qty',
            'product_name_lenght',
            'product_description_lenght'
        ]]
        .drop_duplicates(subset=['product_id'])
        .reset_index(drop=True)
    )
    return dim_product_df

In [ ]:
#build product dimension dataframe
dim_product_df=build_dim_product(df_products)
dim_product_df.head()

,product_id,product_category_name,product_category_name_english,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_photos_qty,product_name_lenght,product_description_lenght
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery,225.0,16.0,10.0,14.0,1.0,40.0,287.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,art,1000.0,30.0,18.0,20.0,1.0,44.0,276.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,sports_leisure,154.0,18.0,9.0,15.0,1.0,46.0,250.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,baby,371.0,26.0,4.0,26.0,1.0,27.0,261.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,housewares,625.0,20.0,17.0,13.0,4.0,37.0,402.0

In [ ]:
#check number of rows of dim_product dataframe
dim_product_df.shape

(32951, 10)

In [ ]:
#fix column name typos from source dataset
dim_product_df=dim_product_df.rename(columns={
    'product_name_lenght':'product_name_length',
    'product_description_lenght':'product_description_length'
})

In [ ]:
#load product dimension into dim.dim_product table
dim_product_df.to_sql(
    name='dim_product',
    con=engine,
    schema='dim',
    if_exists='append',
    index=False
)

951

In [ ]:
#verify rows loaded in dim_product table
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_product',
    engine
)

   row_count
0      32951

In [421]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_duration_days         96476 non-null  float64
 9   is_late_delivery               99441 non-null  bool
 10  is_failed_order                99441 non-null  bool
dtypes: bool(2), category(1), datetime64[ns](5), float64(1), object(2)
memory usage: 6.4+ MB

In [ ]:
#function to build orders fact table
def build_fact_orders(df_orders, df_customers, engine):

    #get customer surrogate keys
    customer_dim = pd.read_sql(
        "SELECT customer_sk, customer_unique_id FROM dim.dim_customer",
        engine
    )

    #get date dimension for date key mapping
    date_dim = pd.read_sql(
        "SELECT date_sk, full_date FROM dim.dim_date",
        engine
    )

    date_dim["full_date"] = pd.to_datetime(date_dim["full_date"]).dt.date

    customer_lookup = df_customers[
        ["customer_id", "customer_unique_id"]
    ]

    #attach customer identifiers to orders dataframe
    fact_df = df_orders.merge(
        customer_lookup,
        on="customer_id",
        how="left"
    )

    #merge with customer dimension
    fact_df = fact_df.merge(
        customer_dim,
        on="customer_unique_id",
        how="left"
    )

    #convert timestamps and map them to date dimension keys
    date_cols = [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]

    for col in date_cols:
        fact_df[col] = pd.to_datetime(fact_df[col]).dt.date

    def resolve_date_sk(df, date_col, sk_name):
        df = df.merge(
            date_dim,
            left_on=date_col,
            right_on="full_date",
            how="left"
        )

        df = df.rename(
            columns={"date_sk": sk_name}
        ).drop(columns=["full_date"])

        return df

    #map order timestamps to date surrogate keys
    fact_df = resolve_date_sk(
        fact_df,
        "order_purchase_timestamp",
        "purchase_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_approved_at",
        "approved_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_delivered_carrier_date",
        "carrier_handoff_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_delivered_customer_date",
        "delivered_customer_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_estimated_delivery_date",
        "estimated_delivery_date_sk"
    )

    #calculate delivery duration from purchase to customer delivery
    fact_df["delivery_duration_days"] = (
        pd.to_datetime(fact_df["order_delivered_customer_date"]) -
        pd.to_datetime(fact_df["order_purchase_timestamp"])
    ).dt.days

    #calculate delivery delay relative to estimated date
    delay = (
        pd.to_datetime(fact_df["order_delivered_customer_date"]) -
        pd.to_datetime(fact_df["order_estimated_delivery_date"])
    ).dt.days
    
    fact_df["delivery_delay_days"] = delay.apply(
        lambda x: x if pd.notnull(x) and x > 0 else 0
    )

    #flag orders that were successfully delivered
    fact_df["is_delivered_flag"] = fact_df["order_status"].eq("delivered")

    #create flags for late deliveries and failed orders
    fact_df["is_late_delivery"] = fact_df["delivery_delay_days"] > 0
    fact_df["is_failed_order"] = fact_df["order_status"].isin(["canceled", "unavailable"])

    #create combined issue indicator
    fact_df["issue_flag"] = (
        fact_df["is_late_delivery"] |
        fact_df["is_failed_order"]
    )

    #select final columns for fact_orders table
    final_cols = [
        "order_id",
        "customer_id",
        "customer_sk",
        "purchase_date_sk",
        "approved_date_sk",
        "carrier_handoff_date_sk",
        "delivered_customer_date_sk",
        "estimated_delivery_date_sk",
        "order_status",
        "delivery_duration_days",
        "delivery_delay_days",
        "is_delivered_flag",
        "is_late_delivery",
        "is_failed_order",
        "issue_flag"
    ]

    return fact_df[final_cols]

In [ ]:
#build orders fact dataframe
fact_orders_df=build_fact_orders(df_orders, df_customers, engine)

In [ ]:
#check the shape of the fact_orders dataframe
fact_orders_df.shape

(99441, 15)

In [ ]:
#load orders fact into fact.fact_orders table
fact_orders_df.to_sql(
    name='fact_orders',
    con=engine,
    schema='fact',
    if_exists='append',
    index=False
)

441

In [ ]:
#verify rows loaded in fact_orders table
pd.read_sql(
    'SELECT COUNT(*) FROM fact.fact_orders',
    engine
)

   count
0  99441

In [ ]:
#function to build order_items fact table
def build_fact_order_items(df_order_items, engine):

    #get product surrogate keys
    product_dim = pd.read_sql(
        "SELECT product_id, product_sk FROM dim.dim_product",
        engine
    )

    #get seller surrogate keys
    seller_dim = pd.read_sql(
        "SELECT seller_id, seller_sk FROM dim.dim_seller",
        engine
    )

    #get date dimension for shipping date mapping
    date_dim = pd.read_sql(
        "SELECT date_sk, full_date FROM dim.dim_date",
        engine
    )

    #get order level keys from fact_orders
    fact_orders_lookup = pd.read_sql(
        """
        SELECT order_id, customer_sk, purchase_date_sk
        FROM fact.fact_orders
        """,
        engine
    )

    date_dim["full_date"] = pd.to_datetime(date_dim["full_date"]).dt.date

    fact_df = df_order_items.copy()

    #attach product surrogate key to the copied order_items datafame
    fact_df = fact_df.merge(
        product_dim,
        on="product_id",
        how="left"
    )

    #attach seller surrogate key
    fact_df = fact_df.merge(
        seller_dim,
        on="seller_id",
        how="left"
    )

    #attach customer and purchase date keys
    fact_df = fact_df.merge(
        fact_orders_lookup,
        on="order_id",
        how="left"
    )

    #convert shipping limit date and map to date_sk
    fact_df["shipping_limit_date"] = pd.to_datetime(
        fact_df["shipping_limit_date"]
    ).dt.date

    fact_df = fact_df.merge(
        date_dim,
        left_on="shipping_limit_date",
        right_on="full_date",
        how="left"
    ).rename(columns={"date_sk": "shipping_limit_date_sk"}).drop(columns=["full_date"])

    #calculate total item value including freight
    fact_df["item_total_value"] = (
        fact_df["price"] + fact_df["freight_value"]
    )

    #select final columns for fact_order_items table
    final_cols = [
        "order_id",
        "order_item_id",
        "product_sk",
        "seller_sk",
        "customer_sk",
        "purchase_date_sk",
        "shipping_limit_date_sk",
        "price",
        "freight_value",
        "item_total_value"
    ]

    return fact_df[final_cols]

In [ ]:
#build orders fact_order_items dataframe
fact_order_items_df=build_fact_order_items(df_order_item_enriched, engine)

In [ ]:
#check the shape of the fact_order_items dataframe
fact_order_items_df.shape

(112650, 10)

In [ ]:
#load fact order items into fact.fact_order_items table
fact_order_items_df.to_sql(
    name='fact_order_items',
    con=engine,
    schema='fact',
    if_exists='append',
    index=False
)

650

In [ ]:
#verify rows loaded in fact_order_items table
pd.read_sql(
    'SELECT COUNT(*) FROM fact.fact_order_items',
    engine
)

    count
0  112650

In [ ]:
#function to build seller-order fact table
def build_fact_seller_order(df_order_items, engine):
    
    #get seller surrogate keys
    seller_dim=pd.read_sql(
        'SELECT seller_sk, seller_id FROM dim.dim_seller',
        engine
    )

    #get order level metrics and flags from fact_orders
    fact_orders=pd.read_sql(
        '''
        SELECT
            order_id,
            customer_sk,
            purchase_date_sk,
            is_delivered_flag,
            is_late_delivery,
            is_failed_order,
            delivery_delay_days
        FROM fact.fact_orders
        ''',
        engine
    )

    #aggregate order_items to seller-order level
    agg=(
        df_order_items
        .groupby(['order_id', 'seller_id'], as_index=False)
        .agg(
            seller_order_revenue=('price', 'sum'),
            seller_order_freight=('freight_value', 'sum'),
            seller_order_items_count=('order_item_id', 'count')
        )
    )

    #attach seller surrogate key
    agg=agg.merge(seller_dim, on='seller_id', how='left')

    #attach order level keys and delivery metrics
    fact_df=agg.merge(fact_orders, on='order_id', how='left')

    #replace missing flags and delay values
    fact_df["is_late_delivery"] = fact_df["is_late_delivery"].fillna(False)
    fact_df["is_failed_order"] = fact_df["is_failed_order"].fillna(False)
    fact_df["is_delivered_flag"] = fact_df["is_delivered_flag"].fillna(False)
    fact_df["delivery_delay_days"] = fact_df["delivery_delay_days"].fillna(0)

    #select final columns for fact_seller_order table
    final_cols=[
        'order_id',
        'seller_sk',
        'customer_sk',
        'purchase_date_sk',
        'seller_order_revenue',
        'seller_order_freight',
        'seller_order_items_count',
        'is_late_delivery',
        'is_delivered_flag',
        'is_failed_order',
        'delivery_delay_days'
    ]
    return fact_df[final_cols]

In [ ]:
#build orders fact_seller_order dataframe
fact_seller_order_df=build_fact_seller_order(df_order_item_enriched, engine)

In [ ]:
#check the shape of the fact_seller_order dataframe
fact_seller_order_df.shape

(100010, 11)

In [ ]:
#load fact_seller_order into fact.fact_seller_order table
fact_seller_order_df.to_sql(
    name='fact_seller_order',
    con=engine,
    schema='fact',
    if_exists='append',
    index=False
)

10

In [134]:
#verify rows loaded in fact_seller_order table
pd.read_sql(
    'SELECT COUNT(*) FROM fact.fact_seller_order',
    engine
)

    count
0  100010

In [ ]:
pd.read_sql(
    '''
    SELECT COUNT(DISTINCT seller_id) AS total_sellers
    FROM dim.dim_seller
    ''',
    engine
)

   total_sellers
0           3095